/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gofish;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author Alex
 */
public class MainGui extends javax.swing.JFrame {

    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeGameGUI = new javax.swing.JButton();
        resetButtonGUI = new javax.swing.JButton();
        helpButtonGUI = new javax.swing.JButton();
        handButton8 = new javax.swing.JButton();
        handButton12 = new javax.swing.JButton();
        handButton11 = new javax.swing.JButton();
        handButton10 = new javax.swing.JButton();
        handButton7 = new javax.swing.JButton();
        handButton6 = new javax.swing.JButton();
        handButton5 = new javax.swing.JButton();
        handButton4 = new javax.swing.JButton();
        handButton3 = new javax.swing.JButton();
        handButton2 = new javax.swing.JButton();
        deckButton = new javax.swing.JButton();
        handButton13 = new javax.swing.JButton();
        handButton1 = new javax.swing.JButton();
        handButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        goFishButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeGameGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/card/X_Button.png"))); // NOI18N
        closeGameGUI.setBorderPainted(false);
        closeGameGUI.setContentAreaFilled(false);
        closeGameGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeGameGUIActionPerformed(evt);
            }
        });
        jPanel1.add(closeGameGUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 40, 40));

        resetButtonGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/card/Reset Button.png"))); // NOI18N
        resetButtonGUI.setToolTipText("");
        resetButtonGUI.setBorderPainted(false);
        resetButtonGUI.setContentAreaFilled(false);
        resetButtonGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonGUIActionPerformed(evt);
            }
        });
        jPanel1.add(resetButtonGUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 40, 40));

        helpButtonGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/card/Menu_Button.png"))); // NOI18N
        helpButtonGUI.setBorderPainted(false);
        helpButtonGUI.setContentAreaFilled(false);
        helpButtonGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonGUIActionPerformed(evt);
            }
        });
        jPanel1.add(helpButtonGUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 40, 40));

        handButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/card/1h.png"))); // NOI18N
        handButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(handButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 70, 90));

        handButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(handButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 510, 70, 90));

        handButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(handButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 510, 70, 90));

        handButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(handButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 70, 90));

        handButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/card/11h.png"))); // NOI18N
        handButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(handButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 70, 90));

        handButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/card/10c.png"))); // NOI18N
        handButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(handButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 70, 90));

        handButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(handButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 70, 90));

        handButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(handButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 70, 90));

        handButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(handButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 70, 90));

        handButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(handButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 70, 90));

        deckButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/card/back.png"))); // NOI18N
        deckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deckButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deckButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 70, 90));

        handButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(handButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 510, 70, 90));

        handButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(handButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 70, 90));

        handButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(handButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, 70, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/card/back.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/card/back.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/card/back.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/card/back.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("2");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("3");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 10, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Score: 0");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NAME");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Deck Count: 45");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        goFishButton.setText("GO FISH");
        goFishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goFishButtonActionPerformed(evt);
            }
        });
        jPanel1.add(goFishButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 640, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Score: 0");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NAME");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/card/Gofishbackground.png"))); // NOI18N
        background.setText("jLabel2");
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpButtonGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonGUIActionPerformed
        // TODO add your handling code here:
        //HelpScreen g = new HelpScreen();
        //g.setVisible(true);
    }//GEN-LAST:event_helpButtonGUIActionPerformed

    private void resetButtonGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonGUIActionPerformed
        // TODO add your handling code here:
        //MainGui g = new MainGui();
        //g.setVisible(true);
        //dispose();
        
        //prolly need to reset deck and hands later lol
    }//GEN-LAST:event_resetButtonGUIActionPerformed

    private void handButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_handButton8ActionPerformed

    private void handButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_handButton12ActionPerformed

    private void handButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_handButton11ActionPerformed

    private void handButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_handButton10ActionPerformed

    private void handButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_handButton7ActionPerformed

    private void handButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_handButton6ActionPerformed

    private void handButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_handButton5ActionPerformed

    private void handButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_handButton4ActionPerformed

    private void handButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_handButton3ActionPerformed

    private void handButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_handButton2ActionPerformed

    private void deckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deckButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deckButtonActionPerformed

    private void handButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_handButton13ActionPerformed

    private void handButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_handButton1ActionPerformed

    private void closeGameGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeGameGUIActionPerformed
        // TODO add your handling code here:
        //System.exit(0);
    }//GEN-LAST:event_closeGameGUIActionPerformed

    private void handButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_handButton9ActionPerformed

    private void goFishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goFishButtonActionPerformed
        // TODO add your handling code here:
        Win_LossScreen g = new Win_LossScreen();
        g.setVisible(true);
    }//GEN-LAST:event_goFishButtonActionPerformed
    void addHelpGameListener(ActionListener helpListener){
        helpButtonGUI.addActionListener(helpListener);        
    }
    void addCloseGameListener(ActionListener helpListener){
        closeGameGUI.addActionListener(helpListener);
        
    }
    void addResetGameListener(ActionListener helpListener){
        resetButtonGUI.addActionListener(helpListener);
        
    }
    void addDeckListener(ActionListener helpListener){
        deckButton.addActionListener(helpListener);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGui().setVisible(true);
            }
        });
    }
    public void setUpButtonListeners(){
        ActionListener buttonListener = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                System.out.println("click");
            
            }
        };
        
        handButton1.addActionListener(buttonListener);
        
        
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton closeGameGUI;
    private javax.swing.JButton deckButton;
    private javax.swing.JButton goFishButton;
    private javax.swing.JButton handButton1;
    private javax.swing.JButton handButton10;
    private javax.swing.JButton handButton11;
    private javax.swing.JButton handButton12;
    private javax.swing.JButton handButton13;
    private javax.swing.JButton handButton2;
    private javax.swing.JButton handButton3;
    private javax.swing.JButton handButton4;
    private javax.swing.JButton handButton5;
    private javax.swing.JButton handButton6;
    private javax.swing.JButton handButton7;
    private javax.swing.JButton handButton8;
    private javax.swing.JButton handButton9;
    private javax.swing.JButton helpButtonGUI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton resetButtonGUI;
    // End of variables declaration//GEN-END:variables
}
